---
- name: Install monitoring tools (Node Exporter)
  hosts: webserver
  become: true

  tasks:
    - name: Download Node Exporter
      get_url:
        url: https://github.com/prometheus/node_exporter/releases/download/v1.7.0/node_exporter-1.7.0.linux-amd64.tar.gz
        dest: /tmp/node_exporter.tar.gz

    - name: Extract Node Exporter
      unarchive:
        src: /tmp/node_exporter.tar.gz
        dest: /opt/
        remote_src: yes

    - name: Create systemd service for Node Exporter
      template:
        src: node_exporter.service.j2
        dest: /etc/systemd/system/node_exporter.service
        mode: 0644

    - name: Start and enable Node Exporter service
      systemd:
        name: node_exporter
        enabled: true
        state: started

    - name: Open port 9100 in firewall
      ufw:
        rule: allow
        port: 9100
        proto: tcp
