---
- name: Update APT package cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install essential packages
  apt:
    name: "{{ packages }}"
    state: present

- name: Allow required ports through UFW
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop: "{{ firewall_ports }}"

- name: Enable UFW firewall
  ufw:
    state: enabled
    policy: allow

- name: Ensure NGINX is running
  service:
    name: nginx
    state: started
    enabled: true
