name: Deploy on Tag

on:
  push:
    tags:
      - 'v*.*.*'   # déclenche sur tout tag comme v1.0.0, v2.5.3...

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Install Ansible
        run: sudo apt install -y ansible

      - name: Deploy to production
        working-directory: ./ansible
        run: ansible-playbook -i inventory.ini setup-api.yml
